apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployments
spec: 
  replicas: 3
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
      - name: portal-noticias
        image: aluracursos/portal-noticias:1
        ports:
        - containerPort: 80
        envFrom: 
          - configMapRef:
              name: portal-configmap
  selector:
    matchLabels:
      app: portal-noticias