apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: sistema-noticias-statefulset
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sistema-noticias
      name: sistema-noticias
    spec:
      containers:
      - name: sistema-noticias-container
        image: aluracursos/sistema-noticias:1
        ports:
        - containerPort: 80
        envFrom: 
          - configMapRef:
              name: sistema-configmap
        volumeMounts:
          - name: imagens
            mountPath: /var/www/html/uploads    # Corrigido de mounthPath para mountPath
          - name: session
            mountPath: /tmp                    # Corrigido de mounthPath para mountPath
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: imagens-pvc
        - name: session
          persistentVolumeClaim:
            claimName: session-pvc
  selector:
    matchLabels:
      app: sistema-noticias
  serviceName: svc-sistema-noticias
