apiVersion: apps/v1
kind: Deployment
metadata:
  name: vollmed
  labels:
    app: vollmed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vollmed
  template:
    metadata:
      labels:
        app: vollmed
    spec:
      containers:
      - name: vollmed-api
        image: lorenzouriel147/vollmed-api:1
        ports:
        - containerPort: 3000
        env:
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: data-vollmed
              key: DB_DATABASE
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: data-vollmed
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-vollmed
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-vollmed
              key: DB_PASSWORD
        livenessProbe:
          httpGet: 
            path: /paciente
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 3